services:
  darthvader:
    build: darthvader
    hostname: darthvader
    networks:
      rededns:
          ipv4_address: 192.168.20.10
    volumes:
      - ./darthvader/conf/named.conf.options:/etc/bind/named.conf.options
      - ./darthvader/conf/etc_default_named:/etc/default/named
      - ./darthvader/conf/named.conf.local:/etc/bind/named.conf.local
      - ./darthvader/conf/db.starwars:/etc/bind/db.starwars
      - ./darthvader/conf/db.192:/etc/bind/db.192

  eq1:
    build: eq1
    hostname: eq1
    dns:
     - 192.168.20.10
    networks:
      rededns:
          ipv4_address: 192.168.20.100
networks:
  rededns:
    ipam:
      config:
        - subnet: 192.168.20.0/24

