services:
  darthvader:
    build: dnsserver
    hostname: darthvader
    networks:
      rededns:
          ipv4_address: 192.168.20.10
    volumes:
      - ./darthvader/conf/named.conf.options:/etc/bind/named.conf.options
      - ./darthvader/conf/etc_default_named:/etc/default/named
      - ./darthvader/conf/named.conf.local:/etc/bind/named.conf.local
      - ./darthvader/conf/db.starwars:/var/cache/bind/db.starwars
      - ./darthvader/conf/db.192:/var/cache/bind/db.192

  darthsidious:
    build: dnsserver
    hostname: darthsidious
    networks:
      rededns:
          ipv4_address: 192.168.20.11
    volumes:
      - ./darthsidious/conf/named.conf.local:/etc/bind/named.conf.local
      - ./darthsidious/conf/named.conf.options:/etc/bind/named.conf.options

  eq1:
    build: debian
    hostname: eq1
    dns:
     - 192.168.20.10
     - 192.168.20.11
    networks:
      rededns:
          ipv4_address: 192.168.20.100
networks:
  rededns:
    ipam:
      config:
        - subnet: 192.168.20.0/24

