services:
  darthvader:
    build: darthvader
    hostname: darthvader
    networks:
      rededns:
          ipv4_address: 192.168.20.10
    volumes:
      - ./darthvader/conf/named.conf.options:/etc/bind/named.conf.options
      - ./darthvader/conf/etc_default_named:/etc/default/named

  #eq1:
  #  build: debian
  #  hostname: eq1
  #  dns:
  #   - 192.168.20.10
  #  networks:
  #    rededns:
  #        ipv4_address: 192.168.20.100
networks:
  rededns:
    ipam:
      config:
        - subnet: 192.168.20.0/24

